### ISSUE TITLE
install clr报错称找不到函数：

### ISSUE THREAD

**Issue by fengtianyunsheng** [co01cat/SqlmapXPlus#7]
install clr报错称找不到函数：
Traceback (most recent call last):
  File "sqlmap.py", line 226, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 243, in action
    conf.dbmsHandler.xpCmdUpload("clrdatabase.dll", "c:\\windows\\tasks\\clrdatabase.dll")
AttributeError: 'MySQLMap' object has no attribute 'xpCmdUpload'

**Comment by fengtianyunsheng** [comment]
感谢解答
