### ISSUE TITLE
How to solve this problem?   --install-clr

### ISSUE THREAD

**Issue by hurtisvagler** [co01cat/SqlmapXPlus#9]
[12:59:58] [INFO] fetching current database
Please input remote dll path
请输入远程目标的dll路径：c:\windows\tasks\clrexec.dll
Please enter the custom CLR assembly name, stored procedure class name, stored procedure function name separately
请分别输入自定义CLR程序集名称 存储过程类名 存储过程函数名：clrexec

[13:00:52] [CRITICAL] unhandled exception occurred in sqlmap/1.8#stable. It is recommended to retry your run with the latest development version from official GitHub repository at 'https://github.com/sqlmapproject/sqlmap'. If the exception persists, please open a new issue at 'https://github.com/sqlmapproject/sqlmap/issues/new' with the following text and any other information required to reproduce the bug. Developers will try to reproduce the bug, fix it accordingly and get back to you
Running version: 1.8#stable
Python version: 3.10.12
Operating system: Linux-5.15.0-113-generic-x86_64-with-glibc2.35
Command line: sqlmap.py -u ************************************************************* --random-agent --install-clr
Technique: UNION
Back-end DBMS: Microsoft SQL Server (fingerprinted)
Traceback (most recent call last):
  File "sqlmap.py", line 226, in main
    start()
  File "lib/core/decorators.py", line 80, in _
    result = f(*args, **kwargs)
  File "lib/controller/controller.py", line 732, in start
    action()
  File "lib/controller/action.py", line 245, in action
    conf.dbmsHandler.installClr(conf.dbmsHandler.getCurrentDb())
  File "plugins/generic/takeover.py", line 87, in installClr
    b,c,d = (input("请分别输入自定义CLR程序集名称 存储过程类名 存储过程函数名：").split())
ValueError: not enough values to unpack (expected 3, got 1)

do you want to automatically create a new (anonymized) issue with the unhandled exception information at the official Github repository? [y/N] > n

[*] ending @ 13:00:58 /2024-08-02/
![Screenshot_50](https://github.com/user-attachments/assets/e8ea41a9-e021-4aee-ad26-c0b1b6f9bf21)

**Comment by co01cat** [comment]
Currently, only “stacked queried” is supported，stacked queried.Need to debug on your own, currently the tool is not very comprehensive.
